[env:freenove-esp32-s3-n8r8]
platform  = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = freenove-esp32-s3-n8r8
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyACM0
build_flags = 
    -std=gnu++17
    -DDBG_LOG
    -DDEBUGLOG_DEFAULT_LOG_LEVEL_TRACE
    -UDEBUG_LOG_DISABLED
lib_deps =
    https://github.com/tzapu/WiFiManager.git#v2.0.17
    bblanchon/ArduinoJson@^7.0.0
    https://github.com/hideakitai/DebugLog.git#v0.8.4
